### ISSUE TITLE
No Image from image_raw showing in Rviz 

### ISSUE THREAD

**Issue by tomaslieven** [tier4/AWSIM#15]
awsim will list all topics ie 

```
/clock
/control/command/control_cmd
/control/command/emergency_cmd
/control/command/gear_cmd
/control/command/hazard_lights_cmd
/control/command/turn_indicators_cmd
/parameter_events
/rosout
/sensing/camera/traffic_light/camera_info
/sensing/camera/traffic_light/image_raw
/sensing/gnss/pose
/sensing/gnss/pose_with_covariance
/sensing/imu/tamagawa/imu_raw
/sensing/lidar/top/pointcloud_raw
/sensing/lidar/top/pointcloud_raw_ex
/vehicle/status/control_mode
/vehicle/status/gear_status
/vehicle/status/hazard_lights_status
/vehicle/status/steering_status
/vehicle/status/turn_indicators_status
/vehicle/status/velocity_status

```

also 
/sensing/camera/traffic_light/image_raw

is echoing and streaming data:
```
---
header:
  stamp:
    sec: 386
    nanosec: 89991370
  frame_id: traffic_light_left_camera/camera_optical_link
height: 720
width: 1280
encoding: bgr8
is_bigendian: 0
step: 3840
data:
- 78
- 70
- 69
- 79
- 72
- 69
- 78
- 72
- '...'
---
```
but i cant get any image in Rviz inside:
/perception/traffic_light_recognition/debug/rois
or /sensing/camera/traffic_light/image_raw on map/base_link or sensor_kit_base_link

![Screenshot from 2022-10-25 23-53-23](https://user-images.githubusercontent.com/10801085/197889860-d75d8a86-852f-49e8-9b4b-ccb9e505bb7d.png)

also topic /sensing/camera/traffic_light/camera_info seems ok
```
header:
  stamp:
    sec: 894
    nanosec: 289980011
  frame_id: traffic_light_left_camera/camera_optical_link
height: 720
width: 1280
distortion_model: plumb_bob
d:
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
k:
- 365.71429443359375
- 0.0
- 640.5
- 0.0
- 365.4822082519531
- 360.5
- 0.0
- 0.0
- 1.0
r:
- 1.0
- 0.0
- 0.0
- 0.0
- 1.0
- 0.0
- 0.0
- 0.0
- 1.0
p:
- 365.71429443359375
- 0.0
- 640.5
- 0.0
- 0.0
- 365.4822082519531
- 360.5
- 0.0
- 0.0
- 0.0
- 1.0
- 0.0
binning_x: 0
binning_y: 0
roi:
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: false
---
```

running ros galactic, tried main or even awsim-stable branches, also unity project all same results not processing camera stream
